version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRAUD_SHIELD_MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./backend:/app

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mongodb_data:
